### PR TITLE
TypeScript modifications, auto-closing dropdown functionality, password visibility modifications

### PR DESCRIPTION
**Pull request by ggreer91**
Add TypeScript to several files, add functionality in Drawer.svelte to automatically close the open dropdown upon choosing an option, rework password visibility in Login.svelte, rename passwordVisible to hidePassword for clarity

### CODE REVIEW

**Comment by vkpatel007** [comment]
Excellent work George. Push it to main!!

**Review by vkpatel007 — APPROVED** [review]

**Review by vkpatel007 — APPROVED** [review]
Great work here! Push it to main!!!

**Review by NikoAmescua — APPROVED** [review]
Nice work George!

**Review by starfishpanda — APPROVED** [review]
Thanks for cleaning this up, George

**Pull request merged**
