### PR TITLE
All metrics charts

### PR DESCRIPTION
**Pull request by NikoAmescua**
- add a page for all query metrics
- add a component bar chart for comparing average query times

### CODE REVIEW

**Comment by vkpatel007** [comment]
Good work on D3 this is usually where engineers run into issues as you are using vanilla dom manipulation. Look forward to see where you go from here!!

**Review by ggreer91 — APPROVED** [review]
Great job with the visualization on the all metrics bar chart.

**Review by cronullarc — APPROVED** [review]
Love it. All the data visualization looks great.

**Comment by vkpatel007** [comment]
Good work on D3 this is usually where engineers run into issues as you are using vanilla dom manipulation. Look forward to see where you go from here!!

**Review by vkpatel007 — APPROVED** [review]
Good work on D3 this is usually where engineers run into issues as you are using vanilla dom manipulation. Look forward to see where you go from here!!

**Review by starfishpanda — APPROVED** [review]
D3 charts are looking great!

**Pull request merged**
