### PR TITLE
Vivek/qc6

### PR DESCRIPTION
**Pull request by vkpatel007**
add fixes, modals, terms and conditions, popups

### CODE REVIEW

**Review by ggreer91 — APPROVED** [review]
Great job! Let's review this together before we merge into dev.

**Comment by cronullarc** [comment]
Looks great! Some great cleanup.

**Review by NikoAmescua — APPROVED** [review]
The code looks good to go!

**Review by starfishpanda — APPROVED** [review]
New graph of all metrics looks clean.

**Pull request merged**
