### PR TITLE
add nav link fix, ER diagram modal, landing page npm update

### PR DESCRIPTION
**Pull request by NikoAmescua**

### CODE REVIEW

**Review by vkpatel007 — APPROVED** [review]
Wow i didn't think you could do it but you did. Great Job!

**Review by ggreer91 — APPROVED** [review]
INCREDIBLE work!

**Review by starfishpanda — APPROVED** [review]
Love the new modal!

**Review by cronullarc — APPROVED** [review]
This looks amazing! Great work.

**Pull request merged**
