### PR TITLE
add landing page visualizer and npm package

### PR DESCRIPTION
**Pull request by vkpatel007**

### CODE REVIEW

**Review by ggreer91 — APPROVED** [review]
The landing page looks amazing! Great job team 🔥

**Review by starfishpanda — APPROVED** [review]
Landing page looking very buttoned up and clear!

**Review by cronullarc — APPROVED** [review]
The landing page is awesome! Great layout.

**Review by NikoAmescua — APPROVED** [review]
Looks really clean!

**Pull request merged**
